### ISSUE TITLE
Result Flags - Flagged Min / Max Values include values with <

### ISSUE THREAD

**Issue by psolberg-usgs** [USGS-R/WQ-Review#110]
This observation is specific to Result Flags for pesticides. 

The RL for pesticide changes a lot, and the max/min flags don't seem to recognize that there are remark codes of < associated with the results, therefore it 'falsely?' flags the values as new mins & max, and greatly expands the 'Result Flag' table.
Ex: station ID 09163500 - look at WY2014.
There are 240 result flags, and ~180 of those are pesticides, with fluctuating RL. 

Any way to consider whether the Remark code is < and then choose to disregard as a max or min flag if Remark code is <?

**Comment by tjmills** [comment]
Yeah this is an issue when there are a lot of censored values. I had not really worried about the remark code for the min max quantile flags. So, for major ions for example if you have a lot of detections and then a low value that was actually a non-detect, its an appropriate flag. But for what you describe, that is no good.

I consider the remark code in some other auto-flagging calculations, but I will have to think about how to do it here. Ignoring values with a < is no good because of the scenario I mentioned above. But clearly the current method is no good either. 

Let me chew on it a bit, but I will make some change. Any ideas are welcome

**Comment by tjmills** [comment]
OK, I implemented a fix and will push up to GRAN soon.

What I did is I ignore < and > values in all min/max/quant flags, and included a new flag "unusualNonDetect".

If less than 5% of the historic approved data at a site (excluding blanks) are non-detects, then a new non-detect generates a flag
