### ISSUE TITLE
Software issue

### ISSUE THREAD

**Issue by landrade-yuma** [USGS-R/WQ-Review#136]
Hello,

I am having issues when I try to pull data for a specific sample (by narrowing down the dates). The software will not find any data and I get the following errors: 

**Site number
09522000
Site number file
Browse... 
No file selected
Project code (optional)

Parameter codes

Parameter groups
Allphysicalcationsanionsnutrientsmicrobiologicalbiologicalmetalsnonmetalspesticidespcbsother organicsradio chemicalsstable isotopessedimentpopulation/community
pCode file
Browse... 
No file selected
Start date 
2015-12-01
End date 
2015-12-31
Server name (DSN) 
nwisaz
Environment DB Number 
01
QA DB Number 
09
Get data
[1] "Problem with data import, please check import criteria"
[1] "No samples exist in your local NWIS database for the date range specified, check data criteria"**

I will keep getting this error even if I change the date selected. I have to close the program and start again with a longer date span in order to get any data.

Thanks for your help.

**Comment by tjmills** [comment]
OK, this is also related to issue #135 . There are no QA samples for that data range so it causes the function to erroneously throw an error that there is no data at all. This has been fixed with #135 and should be available for download early next week.

Regarding your 2nd issue with the change in date range having no effect, I have not been able to reproduce this error so am closing. If it continues on other machines in your office let me know. This is hopefully related to the lack of QA samples, which is now fixed.
