### ISSUE TITLE
Data import fails when no QA data available

### ISSUE THREAD

**Issue by tjmills** [USGS-R/WQ-Review#69]
I am no sure where in the data import this error is being generated but when no QA data is present, or the QA database number is incorrect, it throws an error "Argument is of length zero"

**Comment by tjmills** [comment]
This actually only occurs when the QA database number is incorrect

**Comment by dhdupre** [comment]
Here's an idea:
All 45 NWIS hosts use db#01 for Environmental data.
Further, all 45 NWIS hosts have a defined "default" QA db# that goes with 01.
Instead of asking users to type in their defaults, how about reading it from the ENV_QA table?

Then, allow for non-default usage by going back to the current structure (perhaps the user must uncheck a box or something) where the user specifically tells the software which 2 db#'s to use.
