### ISSUE TITLE
Provide option for any DOY plot to display either Calendar or Water year

### ISSUE THREAD

**Issue by johnseostman** [USGS-R/WQ-Review#89]
This would better integrate with hydrograph comparison especially in northern regions and be a benefit in modelling exercises.
jostman@usgs.gov

I don't see where the "enhancements" flag, etc are located

**Comment by tjmills** [comment]
Oddly enough this is not straight forward to do because the day of year would have to be calculated first by day of water year, which is not a function in the package I currently use (lubridate) to return the day of year from the date. Thus, I would need to switch packages since I do not want to add an additional dependency.

**Comment by johnseostman** [comment]
Joe,

I must be registered in github using my personal email.

I have run into the same issue with package lubridate.

Could a 'day of year' or 'year' (setup for WY) vector be added that could
cbind on the fly to any timeseries dataframe and be used to sort against?

Thank you for the reply.

Johnse Ostman
jostman@usgs.gov

**Comment by tjmills** [comment]
Yeah something along those lines could work. Like...

``` r
wyDates <- seq(from=as.Date("2001-10-01"),to=as.Date("2002-09-30"),by="day")
wyDays <- data.frame(doyDay = yday(wyDates),
                     wyDay = seq(from=1,to=length(wyDates),by=1)
)
```

But it won't handle leap years. However, that is probably OK for this application so maybe I will just go with that as a quick and dirty fix for now.
