### ISSUE TITLE
Diamond symbol in plots.

### ISSUE THREAD

**Issue by dcalhoun-usgs** [USGS-R/WQ-Review#92]
Would it be possible to engineer a better "diamond" symbol for representing the estimated (E) values in plots?
What I am seeing in graph outputs is pretty wonky at present. It may be a problem with just having .png as the option. .jpg may work better if it were available.
I can't figure out how to label these comments as Enhancements or otherwise; sorry. Feel free to add if you can. I am just not seeing the ability to add that.

**Comment by tjmills** [comment]
Yeah I have also noticed that they get all wonky when saved as pngs. I will try out a different symbol, but I suspect it also might be a little wonky. For now its a low priority because its an aesthetic thing since the plots are not meant to be exported for distribution outside of USGS review.

Regarding labels I think only I can add them as the admin of this repo.
Thanks for posting!
