### ISSUE TITLE
Possibility of having 2 constituents plot on one or both axes in P vs P plots

### ISSUE THREAD

**Issue by psolberg-usgs** [USGS-R/WQ-Review#99]
Scenario: Lab SC is occasionally requested due to issues with fld SC. Since there are so few Lab SCs it is not easy to QA 'constituents vs SC' very quickly. If you could plot both fld SC (00095) and (90095) on one axes, and plot the other constituents, it would be a much quicker QA. Different symbols would be necessary for the two parameters plotted on the same axes.

**Comment by tjmills** [comment]
I can add multiple parameters to one axis as an option,  but I can't add different symbology because the symbol is already mapped to the remark code and color to medium code. Secondary axis is also not possible (I know, its extremely irritating that the package won't do them easily). You could still distinguish points by hovering or clicking and reading the parameter code.

So, if you think it would still be useful to have multiple parms I can add that in.
